### ISSUE TITLE
Cradle generates a top face when greater than cut radius

### ISSUE THREAD

**Issue by SilentZephyr02** [medicationforall/spoolpowerapp#1]
When the Cradle height is a lot greater than Spool cut radius, the cradle generates a top face (blocking the spool from sitting in the cradle)

Noticed this with Spool cut radius 46.90 and Cradle height greater that 52.00

**Comment by medicationforall** [comment]
Thank you for submitting the issue!

I'm going to use https://spoolpower.streamlit.app/ to prove it out. Leaving everything else as is with a cut radius of 46.90 and a cradle height of 70 I get the following.

![Untitled](https://github.com/medicationforall/spoolpowerapp/assets/19323166/f2a35037-5d44-401b-b90c-88515a50d02e)

For the sake of the cut operation from the cradle I don't need a spool with the center hole cut out. I think I'll make generating the spool with or without the center hole an option and at the the time of creating the cradle I'll leave the center hole out.

I'll update the ticket further once the change is in place

**Comment by medicationforall** [comment]
I went with explicit over implicit

This is the normal spool build method
```python
    def build(self):
        super().build()
        scene = (
            cq.Workplane("XY")
            .union(self.outline)
            .cut(self.cut_hole)
            .cut(self.cut_wall)
            .cut(self.cut_wall.translate((
                0,
                0,
                self.internal_z_translate
            )))
        )
        return scene
```

This is the line that removes the center hole
```python
.cut(self.cut_hole)
```

I added a new build method that does not remove the center hole.
I wanted an explicit build spool method when making the cradle. I didn't want to set a class parameter to false, call build() and then have to set the boolean parameter back to true.

```python
    def build_no_center(self, ):
        super().build()
        scene = (
            cq.Workplane("XY")
            .union(self.outline)
            .cut(self.cut_wall)
            .cut(self.cut_wall.translate((
                0,
                0,
                self.internal_z_translate
            )))
            
        )
        return scene
```

The Cradle class when given a spool as a parent on the make() call now uses the spool.build_no_center() method.
```python
            cut_spool = (
                self.parent.build_no_center()
                .rotate((1,0,0),(0,0,0),90)
                .translate((0,0,self.parent.radius))
            )
```

---

I also added a tall cradle example to better illustrate the use case.

```python
import cadquery as cq
from cqspoolterrain import Spool,Cradle

bp_spool = Spool()
bp_spool.make()
spool_ex = (
      bp_spool.build()
      .rotate((1,0,0),(0,0,0),90)
      .translate((0,0,bp_spool.radius))
)

bp = Cradle()
bp.height = 70
bp.angle = 45
bp.make(bp_spool)
cradle_ex = bp.build().translate((0,0,bp.height/2))

show_object(cradle_ex)
show_object(spool_ex.translate((0,0,2)))
#cq.exporters.export(cradle_ex,"stl/cradle_tall.stl")
```

The generated cradle looks like this
![01](https://github.com/medicationforall/spoolpowerapp/assets/19323166/a697c15d-d880-486b-83da-4f89dcd4e88a)

With the spool it looks like this
![02](https://github.com/medicationforall/spoolpowerapp/assets/19323166/883cace3-1e59-4193-bd0c-4e0510fd777d)

**Comment by medicationforall** [comment]
Code changes went in against cqspoolterrain I got confused for a moment and assumed this issue was reported against that repo. I wrote up my responses presuming that as the frame of reference.
https://github.com/medicationforall/cqspoolterrain/commit/3e0123f6b39f6873ffdaed618a413ee4be46eb17


https://github.com/medicationforall/cqspoolterrain/tree/1.2.1
## 1.2.1
* Spool added build_no_center() method to make the spool without the center hole cut out.
* Upgdated Cradle to use the spool build_no_center build method when generating it's cut spool.
* Added example spool_no_center.py
* Added example cradle_tall.py example
* Updated cradle example to pass in the spool as a parent on the make() call.

**Comment by medicationforall** [comment]
@SilentZephyr02 
* I tested the changes locally
* I updated and rebooted the streamlit instance https://spoolpower.streamlit.app/
  * Tested the changes

![03](https://github.com/medicationforall/spoolpowerapp/assets/19323166/761787de-ac37-4559-afa8-a3ee914ef9b4)

If you are running off of the the streamlit app url
Please refresh the page and verify if the issue is resolved. 

If you are running locally you'll have to pull down the updates. and pip install the latest version of cqspoolterrain
